name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - develop
      - main

env:
  WORKING_DIRECTORY: application

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: application/package.json
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Node Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build storybook
        run: pnpm run build-storybook
      - name: Upload Documents
        uses: actions/upload-pages-artifact@v3
        with:
          # 絶対パスを指定
          path: ${{ env.WORKING_DIRECTORY }}/storybook-static

  # GitHub Pagesにアーティファクトをデプロイ
  # deploy-pagesアクションのみに必要な権限を付与するため、別のジョブとして定義
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4